
worker_processes auto;


http {
	server {
		listen              443 ssl;
        keepalive_timeout   70;
		ssl_session_timeout 3600m;

        ssl_protocols       TLSv1.2 TLSv1.3;
		ssl_ciphers         AES128-SHA:AES256-SHA:RC4-SHA:DES-CBC3-SHA:RC4-MD5;

		location / {
			proxy_pass http://wordpress:9000
		}
	}

}


